server:
  port: 8080

spring:
  application:
    name: pontointeligente
  profiles:
    active: test
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ponto_inteligente
    username: maykel
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        id:
          new_generator_mappings: false

---

spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        id:
          new_generator_mappings: false
  flyway:
    enabled: false
