server:
  port: 8080

spring:
  application:
    name: pontointeligente
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ponto_inteligente
    username: maykel
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        id:
          new_generator_mappings: false
